# Generated by Django 5.0.4 on 2024-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderproduct_color_remove_orderproduct_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promotions',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
