# Generated by Django 5.0.4 on 2024-06-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='promotions',
        ),
    ]
