# Generated by Django 5.0.4 on 2024-07-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Thành phố'),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi chú đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phường/Xã'),
        ),
    ]
