# Generated by Django 5.0.4 on 2024-07-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Giỏ hàng', 'verbose_name_plural': 'Giỏ hàng'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Sản phẩm trong giỏ', 'verbose_name_plural': 'Sản phẩm trong giỏ'},
        ),
    ]
