# Generated by Django 5.0.4 on 2024-05-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
