# Generated by Django 5.0.4 on 2024-07-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_date_joined_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': 'Tài khoản'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Thông tin người dùng', 'verbose_name_plural': 'Thông tin người dùng'},
        ),
    ]
