# Generated by Django 5.0.4 on 2024-06-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
